### ISSUE TITLE
Indonesian format

### ISSUE THREAD

**Issue by ahmadfadlydziljalal** [trntv/yii2-datetime-widget#11]
Dear..

How to add indonesian format in "phpDatetimeFormat",
which is dd-MM-yyyy HH:MM ?

**Comment by ahmadfadlydziljalal** [comment]
Also, in my database, I have field : 2016-10-25 09:00:00

My app in this case will be updated this datetime, but why, the date viewing : 25/10/2016 16:00
even I use phpDatetimeFormat : "dd/MM/yyyy HH:mm"

**Comment by trntv** [comment]
+7 is an issue with your timezone settings, try to add T to your format to see current timezone

Change this to change format:
```php
<?php echo trntv\yii\datetime\DateTimeWidget::widget([
    'phpDatetimeFormat' => 'dd-MM-yyyy HH:mm',
    'phpMomentMapping' => [
        'dd-MM-yyyy HH:mm' => 'DD-MM-YYYY HH:mm'
]
]) ; ?>
```
