### ISSUE TITLE
Bootstrap 4 support 

### ISSUE THREAD

**Issue by dungphanxuan** [trntv/yii2-datetime-widget#17]
Bootstrap 4 not showing picker
![image](https://user-images.githubusercontent.com/10725732/40870496-1730211e-665b-11e8-84e9-6c3eea9d55c5.png)

**Comment by dungphanxuan** [comment]
i customize so work 
![image](https://user-images.githubusercontent.com/10725732/40894391-672feda6-67d3-11e8-9a78-87c15750a040.png)

**Comment by mgrechanik** [comment]
@dungphanxuan, pity you did not share your solution. 
This widget does not work with modern yiisoft/bootstrap5
